### PR TITLE
Set version requirement for Pyhon to >=3.10

### PR DESCRIPTION
**Pull request by Rosi2143**
Current code does not work with Python 3.9.

Requirement has been changed in setup.cfg

### CODE REVIEW

**Comment by wlcrs** [comment]
Please note that this repository is just a mirror of https://gitlab.com/Emilv2/huawei-solar/ . I can't merge them here. Can you create your PR's there instead ?

**Comment by Rosi2143** [comment]
Sure will do.

**Comment by Rosi2143** [comment]
Done: https://gitlab.com/Emilv2/huawei-solar/-/merge_requests/12

**Comment by Rosi2143** [comment]
Thanks

**Pull request closed without merging**
